version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - '3306:3306'
  web:
    build: .
    command: foreman start -f Procfile.dev
    volumes:
      - .:/myapp
    ports:
      - '3000:3000' # puma
      - '8080:8080' # webpack-dev-server
    depends_on:
      - db
